<?php

function title() {
	return "Version";
}

function render() {
	global $last_version;
	global $versions;
	global $todos;
	
	$version = $_GET["version"];

	if (file_exists("v$version") && strpos($version, "..") === false && strpos($version, "/") === false) {
?>
				<h1>
					Version <?= version_format($version) ?>
					
						<?php
		if ($version == $last_version) {
?>
							<badge>Latest</badge>
							<?php
		} else if (!version_successful($version)) {
?>
								<badge danger>Failed Build</badge>
								<?php
		}
?>

				</h1>
		
		<p>
			Built on <?= version_builddate($version) ?>. Version released <?= format_timespan(version_build_timestamp($version), version_build_timestamp(version_successful_before($version))) ?> after <?= version_format(version_successful_before($version)) ?>
		</p>

		<section>
			<a button href="v<?=$version?>/boot">
				<i class="la la-power-off"></i> Boot
			</a>
			
			<?php 
			
			if (version_size($version)) {
			
			?>
			<a button thin href="v<?=$version?>/release.zip">
				<i class="la la-download"></i> Download (<?= format_size(version_size($version)) ?>)
			</a>
			<?php
			
			}
			
			?>
		</section>
		
		<row>
			<col-4>
				<h2>
					<i class="la la-photo"></i> Screenshots
				</h2>

				<p>
					Autogenerated screenshots
				</p>
				
				<?php
		foreach (scandir("v$version") as $file) {
			if ($file[0] != "." && pathinfo($file, PATHINFO_EXTENSION) == "png" && $file != "screenshot-cover.png") {
?>
				<img w-100 src="<?="v$version/$file"?>" />
				<icaption>
					<?=$file?>
				</icaption>
				
				<?php
			}
		}
		?>
				
				<h2>
					<i class="la la-check"></i> Done Tasks
				</h2>
				
				<row>
				
				<?php
																	   
																	   $found = false;
																	   
		foreach ($todos as $todo) {
			if (isset($todo->release) && $todo->release == $version) {
				$found = true;
				
				?>
					
					<col-3>
					
					<?php
				render_todo($todo, false);
				?>
					
						</col-3>
					
					<?php
			}
		}
																	   
																	   if (!$found) {
																		   ?>
					<col-auto>
						<p>
							No tasks with release tag <?= $version ?> found
						</p>
					</col-auto>
					
					<?php
																	   } 
?>
				</row>
				
			</col-4>
			
			<col-2>
				<h2>
					<i class="la la-bars"></i> Changes
				</h2>

				<p>
					Changes parsed from <a href="<?=" v$version/boot/changes " ?>">changes file</a>
				</p>

				<ul>
					<?= version_changes($version) ?>
				</ul>
				
				<hr />

				<h2>
					<i class="la la-file"></i> Log Files
				</h2>
				
				<p>
					Automatically generated logfiles from testing (./test in deploy)
				</p>

				<ul>
					<li>
						<a href="<?="v$version/initial.log" ?>">
							After Boot (<?=floor(filesize("v$version/initial.log") / 10) / 100 ?> KB)
						</a>
					</li>
					<li>
						<a href="<?="v$version/final.log" ?>">
							Final (<?=floor(filesize("v$version/final.log") / 10) / 100 ?> KB)
						</a>
					</li>
				</ul>
				
				<hr />

				<h2>
					<i class="la la-power-off"></i> Boot with Root
				</h2>
				
				<p>
					Boots W2000 v<?= $version ?> with a additional root
				</p>

				<select onchange="location.href = this.value">
					<option selected disabled>
						Select Root...
					</option>
					
					<?php
		foreach (array_reverse(scandir("../win-roots")) as $root) {
			if ($root[0] != "." && is_dir("../win-roots/$root") && $root != "undefined") {
				$info = json_decode(file_get_contents("../win-roots/$root/info.json"));
?>
					<option value="v<?=$version?>/boot/?<?= urlencode($info->root) ?>">
						<?=$info->name?>
					</option>
<?php
			}
		}
?>
				</select>
				
				<hr />
				
				<h2>
					<i class="la la-cog"></i> Gen-Properties
				</h2>
				
				<p>
					Autogenerated properties from <a href="?source=/fs/c/windows/ime/gen&source-version=<?= $version ?>">c/windows/ime/gen</a>. These will be automatically included when booting
				</p>
				
				<?php
		
								   foreach (scandir("v$version/boot/fs/c/windows/ime/gen") as $env) {
									   if ($env[0] != ".") {
										   $name = explode(".prop", explode(".js", $env)[0])[0];
										   
										   if (pathinfo($env, PATHINFO_EXTENSION) == "prop") {
											   $content = file_get_contents("v$version/boot/fs/c/windows/ime/gen/$env");
											   
										   	?>
				
				<key-value>
					<key>
						<?= $env ?>
						
						<a href="?source=/fs/c/windows/ime/gen/<?= $env ?>&source-version=<?= $version ?>">
							<i class="la la-file"></i> View Source
						</a>
					</key>
					<value>
						<?= trim($content) ? $content : "<i>Empty</i>" ?>
					</value>
				</key-value>
				
				<?php
										   } else if (pathinfo($env, PATHINFO_EXTENSION) == "js" && !file_exists("v$version/boot/fs/c/windows/ime/gen/$name.prop")) {
											   ?>
				
				<key-value>
					<key>
						<?= $env ?>
						
						<a href="?source=/fs/c/windows/ime/gen/<?= $env ?>&source-version=<?= $version ?>">
							<i class="la la-file"></i> View Source
						</a>
					</key>
					<value>
						<i>Complex Property</i>
					</value>
				</key-value>
				
				<?php
										   }
									   }
								   }
								   
								   ?>
				
				<hr />
				
				<h2>
					<i class="la la-clone"></i> Diff
				</h2>
				
				<p>
					Compare source to another versions source
				</p>

				<form action="." method="get">
					<input type="hidden" name="diff" value="<?= $version ?>" />
					
					<select name="diff-to" onchange="document.forms[0].submit()">
						<option selected disabled>
							Select Version...
						</option>
						
					<?php
		
		foreach (array_reverse($versions) as $v) {
			if ($version != $v) {
?>
						<option value="<?= $v ?>">v<?= $v ?></option>
					<?php
			}
		}
?>
						</select>
				</form>
				
				<hr />
				
				<h2>
					<i class="la la-signal"></i> Automatic Tests
				</h2>

				<p>
					Tests from tests/assert are tested with assert.dll
				</p>

<?php
		$tests = version_tests($version);
		
		if ($tests) {
			foreach ($tests as $test) {
?>
				<test <?= $test->success ? "success" : "failed" ?>>
					<i class="la la-<?= $test->success ? "check" : "close" ?>"></i> <?= $test->name ?>
					<a href="?test=<?= $test->name ?>&test-version=<?= $version ?>">
						<i class="la la-signal"></i> View
					</a>
				</test>
<?php
			}
		} else {
?>

				<box>
					<i>No tests run</i>
				</box>

<?php
		}
?>
				
				<hr />
				
				<h2>
					<i class="la la-code-fork"></i> Included Programs
				</h2>
				
				<?php
				
				if (version_programs_supported($version)) {
				
				?>
				
				<p>
					These programs (.exe) are shipped with W2000 <?= version_format($version) ?>. Click on Open to start the program in W2000
				</p>
				
				<box>
					<?php
								   
								   foreach (version_programs("v$version/boot/") as $program) {
									   ?>
					
					<key-value>
						<key>
							<?= $program->version ?> 
							
							<a href="?source=<?= "$program->path/$program->file" ?>&source-version=<?= $version ?>">
								<i class="la la-file"></i> View Source
							</a>
							
							<a href='<?= "v$version/boot/?+*[\"" . join("/", array_slice(explode("/", $program->path), $program->path[0] == "/" ? 2 : 1)) . "/$program->file\"]" ?>'>
								<i class="la la-file"></i> Open
							</a>
						</key>
						<value>
							<img pixelated src="<?= icon($program->icon, 16) ?>" />
							<?= $program->name ?>
						</value>
					</key-value>
					
					<?php
								   }
								   
								   ?>
				</box>
				
				<?php
				
				} else {
				
				?>
				
				<p>
					Scanning for programs not supported in this version
				</p>
				
				<?php
				
				}
				
				?>
				
				<hr />
				
				<h2>
					<i class="la la-bank"></i> Included Libraries
				</h2>
				
				<?php
				
				if (version_libraries_supported($version)) {
				
				?>
				
				<p>
					Following libraries are packed into W2000 <?= version_format($version) ?>. Click Inspect to boot W2000 with dev tools and view the DLL in dllexp.exe
				</p>
				
				<box>
					<?php
								   
								   foreach (version_libraries("v$version/boot/") as $lib) {
									   ?>
					
					<key-value>
						<key>
							<?= $lib->version ?>
							
							<a href="?source=<?= "$lib->path/$lib->file" ?>&source-version=<?= $version ?>">
								<i class="la la-file"></i> View Source
							</a>
							
							<a href='<?= "v$version/boot/?+!/win-roots/dev&*[\"x/dllexp.exe\",\"" . join("/", array_slice(explode("/", $lib->path), $lib->path[0] == "/" ? 2 : 1)) . "/$lib->file\"]" ?>'>
								<i class="la la-file"></i> Inspect
							</a>
						</key>
						<value><?= $lib->file ?> / <?= $lib->name ?></value>
					</key-value>
					
					<?php
								   }
								   
								   ?>
				</box>
				
				<?php
				
				} else {
				
				?>
				
				<p>
					Scanning for libraries not supported in this version
				</p>
				
				<?php
				
				}
				
				?>
			</col-2>
		</row>
		
				<?php
    } else {
?>
		Version does not exist!
					<?php
    }
}

?>